#!/bin/bash
umask 077 ; cfgdir=/etc/wireguard ; mkdir -p $cfgdir

_ip2mask() { # convert ip/cidr to netmask: 192.168.1.1/16 -> 192.168.0.0/16
	echo $1 | awk -F'[./]' 'function b(n,at){return int(n/2^at)-int(n/2^(at+8))*256} {n=$1*(2^24)+$2*(2^16)+$3*(2^8)+$4; msk=2^(32-$5); n=int(n/msk)*msk; printf "%u.%u.%u.%u/%s", b(n,24), b(n,16), b(n,8), b(n,0), $5;}'
}

_readopts() { # read options opt=var so they accessible as $opt
	while [ ! -z "$1" ] ; do # some kind of magic
		[[ $opts =~ (^| )${1%=*}($| ) ]] && eval ${1%=*}=${1#*=} || { echo "Unknown option $1"; exit 1; }
		shift
	done
}

up() { # brings iface up and configures related stuff
	iface=${1?"IFACE is missing"}
	read addr port < $cfgdir/$iface.iface
	net=$(_ip2mask $addr)
	cfg="listen-port $port private-key $cfgdir/$iface.key"
	for i in $cfgdir/*.$iface.peer ; do
		read key ips _ _ _ < $i
		cfg="$cfg peer $(echo $key | wg pubkey) allowed-ips $ips"
	done
	ip link add $iface type wireguard
	wg set $iface $cfg
	ip link set dev $iface up
	ip addr add $addr dev $iface
	sysctl -q net.ipv4.ip_forward=1
	iptables -t nat -A POSTROUTING -s $net -o $(ip r l 0/0 | awk '{print $5}') -j MASQUERADE
}

down() { # brings iface down
	iface=${1?"IFACE is missing"}
	read addr port < $cfgdir/$iface.iface
	net=$(_netmask $addr)
	iptables -t nat -D POSTROUTING -s $net -o $(ip r l 0/0 | awk '{print $5}') -j MASQUERADE
	ip link set dev $iface down
	ip link del $iface
}

addlink() { # creates new vpn records
	iface=${1?"IFACE is missing"}; addr=${2?"ADDR is missing"}
	wg genkey > $cfgdir/$iface.key
	shift 2; opts=(port) _readopts $*
	echo "$addr ${port-51820}" > $cfgdir/$iface.iface
}

showpeer() { #shows config and qr code for peer
	name=${1?"NAME is missing"}; iface=${2?"IFACE is missing"}
	read key addr port dns allowed ka < $cfgdir/$name.$iface.peer
	read srvkey < $cfgdir/$iface.key
	read _ srvport < $cfgdir/$iface.iface
	srvip="$(ip r g 1.1.1.1 | awk '/1.1.1.1/ {print $7}'):$srvport"
	srvpubkey=$(echo $srvkey | wg pubkey)
	cfg="[Interface]\nAddress=$addr\n$([ _$port != _0 ] && echo "ListenPort=$port")PrivateKey=$key\nDNS=$dns\n\n[Peer]\nPublicKey=$srvpubkey\nAllowedIPs=$allowed\nEndpoint=$srvip\nPersistentKeepalive=$ka"
	printf "\n\n$cfg\n\n"
	[ ! -z "$(which qrencode)" ] && { printf "$cfg" | qrencode -t ansiutf8; }
}

addpeer() { # creates a record for new peer
	name=${1?"NAME is missing"}; iface=${2?"IFACE is missing"}; addr=${3?"ADDR is missing"}
	shift 3; opts=(port dns allow ka) _readopts $*
	echo "$(wg genkey) $addr ${port-0} ${dns-8.8.8.8,8.8.4.4} ${allow-0.0.0.0/0} ${ka-25}" > $cfgdir/$name.$iface.peer
	showpeer $name $iface
}

help() { cat <<EOF
USAGE
wgctl <up|down> <IFACE>
	| addlink <NAME> <ADDR> [port=<PORT>]
	| addpeer <NAME> <IFACE> <ADDR> [port=<PORT>] [dns=<DNS1,DNS2,...>] [allow=<IP1,IP2,...>] [ka=<KEEPALIVE>]
	| showpeer <NAME> <IFACE>"
	| help
EOF
}

cmd=${1-help}; shift; $cmd $*
